
# The number from the first 10 positive numbers starting from 0
print("First 10 positive even numbers starting from 0")

for i in range(0, 20, 2):

    print(i, end=" ")

print("\n")




# numbers from 5 to 15
print("Numbers from 5 to 15, inclusive")

for i in range(5, 16):

    print(i, end=" ")

print("\n")



# numbers from 100 down to 50 counting by -5
print("Numbers from 100 down to 50, counting by -5")

for i in range(100, 49, -5):

    print(i, end=" ")

print()